title:            muditgoyal
description:      who is muditgoyal
url:              https://muditgoyal.com
permalink:        pretty
timezone:         America/Los_Angeles
sass:
  sass_dir: assets
  style: :compressed
collections:
  - notes
